import {
  formatProposalEstimate,
  resolveProposalEstimate,
} from "@/features/proposal-editor/proposal-estimate";
import type { LeadProposalDraft } from "@/features/proposal-editor/lead-proposal.types";
import type { ClientLeadDetail } from "@/types";

/**
 * Renderer-neutral description of the exported proposal.
 *
 * Both the PDF and DOCX renderers consume this one model, so the document
 * structure is defined exactly once. Writing the layout twice is how the two
 * formats silently drift apart — a section added to one and forgotten in the
 * other. Neither renderer reads the draft directly.
 *
 * Blocks are intentionally primitive (paragraphs, bullets, tables) because that
 * is the intersection of what both pdfmake and docx express natively.
 */

export type DocBlock =
  | { kind: "paragraph"; text: string }
  | { kind: "bullets"; items: string[] }
  | { kind: "table"; columns: string[]; rows: string[][] }
  | { kind: "note"; text: string };

export type DocSection = {
  /** Rendered as a numbered heading in both formats. */
  heading: string;
  blocks: DocBlock[];
};

export type ProposalCoverPage = {
  projectTitle: string;
  clientName: string;
  company: string;
  preparedBy: string;
  date: string;
};

export type ProposalDocument = {
  cover: ProposalCoverPage;
  sections: DocSection[];
  /** Repeated in the footer of every page alongside the page number. */
  footerText: string;
  /** Used for the download filename. */
  fileBaseName: string;
};

export const FOOTER_TEXT = "Generated by AI Software Consultant";

/** Shown verbatim when the commercial section has no real pricing content. */
export const PRICING_PLACEHOLDER =
  "Commercial pricing will be finalized separately.";

/**
 * The prefilled commercial text is a to-do note for the admin, not client-ready
 * copy. If it hasn't been replaced, the spec's placeholder is emitted instead so
 * an unfinished internal note can never reach a client.
 */
const PLACEHOLDER_MARKERS = [
  "to be completed",
  "add the applicable rate card",
];

function isUnfinishedPricing(value: string): boolean {
  const normalized = value.trim().toLowerCase();
  if (normalized.length === 0) return true;
  return PLACEHOLDER_MARKERS.some((marker) => normalized.includes(marker));
}

/**
 * Splits authored text into blocks.
 *
 * The editor's fields are plain text / light markdown, so lines beginning with
 * `-` or `*` become bullets and everything else becomes paragraphs. Runs of
 * bullets are grouped into a single list rather than one list per line.
 */
function textToBlocks(value: string): DocBlock[] {
  const lines = value.split("\n");
  const blocks: DocBlock[] = [];
  let bullets: string[] = [];

  const flushBullets = () => {
    if (bullets.length > 0) {
      blocks.push({ kind: "bullets", items: bullets });
      bullets = [];
    }
  };

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (line.length === 0) {
      flushBullets();
      continue;
    }

    if (/^[-*]\s+/.test(line)) {
      bullets.push(line.replace(/^[-*]\s+/, ""));
      continue;
    }

    flushBullets();
    // Strip leading markdown heading marks — the exported document supplies its
    // own heading hierarchy and nested "###" would read as literal characters.
    blocks.push({ kind: "paragraph", text: line.replace(/^#{1,6}\s*/, "") });
  }

  flushBullets();
  return blocks;
}

function listToBlocks(items: string[], emptyText: string): DocBlock[] {
  if (items.length === 0) {
    return [{ kind: "note", text: emptyText }];
  }
  return [{ kind: "bullets", items }];
}

function sanitizeFileName(value: string): string {
  return (
    value
      .replace(/[^a-z0-9]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "proposal"
  );
}

export function buildProposalDocument(
  draft: LeadProposalDraft,
  lead: ClientLeadDetail,
  preparedBy: string,
): ProposalDocument {
  const includedFeatures = draft.features.filter((feature) => feature.included);

  const commercialBlocks: DocBlock[] = isUnfinishedPricing(draft.pricingNotes)
    ? [{ kind: "paragraph", text: PRICING_PLACEHOLDER }]
    : textToBlocks(draft.pricingNotes);

  // Project Estimate, placed first — right after the cover's Client Information —
  // so it leads the document, exactly as on screen. Uses this version's edited
  // estimate when present, else the lead's frozen snapshot. No AI, no Cost Engine.
  const estimate = formatProposalEstimate(
    resolveProposalEstimate(draft.projectEstimate, lead),
  );
  const techStackBlock: DocBlock =
    estimate.techStack.length > 0
      ? { kind: "bullets", items: estimate.techStack }
      : { kind: "note", text: "Not recorded for this request." };

  const projectEstimateSection: DocSection = {
    heading: "Project Estimate",
    blocks: [
      {
        kind: "table",
        columns: ["Estimate", "Value"],
        rows: [
          ["Estimated Project Cost", estimate.costRange ?? "To be confirmed"],
          ["Estimated Timeline", estimate.timelineRange],
          ["Estimated Hours", `${estimate.estimatedHours} hours`],
          ["Complexity", estimate.complexityLabel],
          [
            "Recommended Team",
            `${estimate.teamSize} member${estimate.teamSize === 1 ? "" : "s"}`,
          ],
        ],
      },
      { kind: "paragraph", text: "Technology Stack" },
      techStackBlock,
      {
        kind: "note",
        text: "Approximate estimate shown to the client at submission. The final quotation may change after detailed requirement analysis.",
      },
    ],
  };

  const sections: DocSection[] = [
    projectEstimateSection,
    {
      heading: "Executive Summary",
      blocks: textToBlocks(draft.executiveSummary),
    },
    {
      heading: "Project Scope",
      blocks: [
        ...listToBlocks(draft.scopeOfWork, "Scope to be confirmed."),
        ...(draft.deliverables.length > 0
          ? ([
              { kind: "paragraph", text: "Deliverables" },
              { kind: "bullets", items: draft.deliverables },
            ] satisfies DocBlock[])
          : []),
      ],
    },
    {
      heading: "Detected Features",
      blocks:
        includedFeatures.length === 0
          ? [{ kind: "note", text: "No features are currently in scope." }]
          : [
              {
                kind: "table",
                columns: ["Feature", "Category", "Priority", "Complexity"],
                rows: includedFeatures.map((feature) => [
                  // Description joins the name cell so the table stays four
                  // columns wide and remains readable in portrait A4.
                  `${feature.name}\n${feature.description}`,
                  feature.category,
                  feature.priority,
                  feature.complexity,
                ]),
              },
            ],
    },
    {
      heading: "Estimated Timeline",
      blocks: textToBlocks(draft.timeline),
    },
    {
      heading: "Team Structure",
      blocks: textToBlocks(draft.teamStructure),
    },
    {
      heading: "Assumptions",
      blocks: textToBlocks(draft.assumptions),
    },
    {
      heading: "Risks",
      blocks: listToBlocks(draft.risks, "No risks recorded."),
    },
    {
      heading: "Commercial Summary",
      blocks: commercialBlocks,
    },
    {
      heading: "Terms & Conditions",
      blocks: textToBlocks(draft.termsAndConditions),
    },
  ];

  return {
    cover: {
      projectTitle: draft.title.trim() || "Project Proposal",
      clientName: lead.name,
      company: lead.company ?? "—",
      preparedBy,
      date: new Intl.DateTimeFormat("en-US", {
        day: "numeric",
        month: "long",
        year: "numeric",
      }).format(new Date()),
    },
    sections,
    footerText: FOOTER_TEXT,
    fileBaseName: sanitizeFileName(draft.title || `${lead.name}-proposal`),
  };
}
