import { Lightbulb } from "lucide-react";

/**
 * Always-visible reassurance card. Stays on screen through every phase — intro,
 * generating and after the images arrive — so the client is never left thinking
 * an AI concept is a commitment to the final UI. Purely informational.
 */
export function MockupInfoNotice() {
  return (
    <div className="rounded-2xl border border-info/25 bg-info-subtle/40 p-4 sm:p-5">
      <div className="flex gap-3.5">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-info-subtle text-info">
          <Lightbulb className="h-5 w-5" strokeWidth={1.85} />
        </div>
        <div className="min-w-0 text-sm leading-relaxed text-foreground-soft text-pretty">
          <p className="font-semibold text-foreground">Good to know</p>
          <p className="mt-1">
            These preview screens are generated by AI to help you picture your idea —
            they are <span className="font-semibold text-foreground">not</span> the
            final application design.
          </p>
          <p className="mt-2">
            Our professional UI/UX designers will create the final interface during the
            design phase, based on your requirements, branding, and business goals.
            Think of these as an early concept, not the finished product.
          </p>
        </div>
      </div>
    </div>
  );
}
